### ISSUE TITLE
Paste delay

### ISSUE THREAD

**Issue by mario-amazing** [hrsh7th/nvim-pasta#2]
Hi, I have paste delay, could you take a look at why could it be?
Configuration same as in README.
Example: 

https://user-images.githubusercontent.com/9537753/188289833-ef028c42-5969-42e0-9df5-bac636f86393.mov

Expected behavior: 
Paste right after press button, same as default p/P behavior.

**Comment by hrsh7th** [comment]
Try `nmap p`

**Comment by mario-amazing** [comment]
@hrsh7th I'm already using:
```lua
map({ 'n', 'x' }, 'p', require('pasta.mappings').p)
map({ 'n', 'x' }, 'P', require('pasta.mappings').P)
```
also I've tried this one with the same delay result.
```lua
map({ 'n' }, 'p', require('pasta.mappings').p)
```

**Comment by ogaken-1** [comment]
Can you switch off the lsp settings and try it?

**Comment by hrsh7th** [comment]
I mean you might set duplicated `p` mapping. So You should check `:nmap p` result. If you have duplicated `p` mapping, it causes the mapping wait.

**Comment by mario-amazing** [comment]
@hrsh7th Nothing only pasta mapping
<img width="286" alt="image" src="https://user-images.githubusercontent.com/9537753/188483406-6b7af50a-3227-4ef9-b452-74fae7bebf2f.png">
@kento-ogata the same delay.

**Comment by hrsh7th** [comment]
I've added the `prevent_diagnostics` option. And it's default value has changed to the `false`.

I think your problem is solved via this change. Could you check this?

**Comment by mario-amazing** [comment]
@hrsh7th, a little bit better, but still have delay..)

**Comment by hrsh7th** [comment]
Probably, the,latest main fixes the problem.

**Comment by mario-amazing** [comment]
@hrsh7th, I have this error:
`.config/nvim/bundle/nvim-pasta/lua/pasta/init.lua:164: attempt to call field 'keycode' (a nil value)`
With default configuration, NVIM v0.9.0.
