### ISSUE TITLE
[Error] attempt to call field 'keycode'

### ISSUE THREAD

**Issue by mario-amazing** [hrsh7th/nvim-pasta#6]
After the latest commit, I have this error:
`.config/nvim/bundle/nvim-pasta/lua/pasta/init.lua:164: attempt to call field 'keycode' (a nil value)`
With default configuration, NVIM v0.9.0.

**Comment by mario-amazing** [comment]
After update the error on the 13 line
`.config/nvim/bundle/nvim-pasta/lua/pasta/init.lua:13: attempt to call field 'keycode' (a nil value)`

**Comment by hrsh7th** [comment]
thank you. I've fixed it.
