### ISSUE TITLE
Should I use this plugin on a stable version of neovim

### ISSUE THREAD

**Issue by Arfs6** [hrsh7th/nvim-pasta#8]
I tried the default setup in the readme, but I was getting an error. It's from vim.keycodes. I later realised vim.keycodes is only available on nvim nightly.
I tried replace_termcodes, it's not showing an error, but pasting with `p` isn't working.
Here is the relevant part of my config:
```	vim.keymap.set({ 'n', 'x' }, 'p', require('pasta.mappings').p)
	vim.keymap.set({ 'n', 'x' }, 'P', require('pasta.mappings').P)
	require('pasta').config.next_key = vim.api.nvim_replace_termcodes('<C-n>', true, true, false)
	require('pasta').config.prev_key = vim.api.nvim_replace_termcodes('<C-p>', true, true, false)
	require('pasta').config.indent_fix = true
```

**Comment by hrsh7th** [comment]
Looks like you forgot to add the `p` mapping.

You can try following snippet.

```
vim.keymap.set({ 'n', 'x' }, 'p', require('pasta.mapping').p)
```

**Comment by Arfs6** [comment]
@hrsh7th I had it, but I naively thought it wasn't relevant.
I have created a minimal config to test:

### `minimal.lua`

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
	"hrsh7th/nvim-pasta",
	config = function()
		vim.keymap.set({ 'n', 'x' }, 'p', require('pasta.mappings').p)
		vim.keymap.set({ 'n', 'x' }, 'P', require('pasta.mappings').P)
		require('pasta').config.next_key = vim.api.nvim_replace_termcodes('<C-n>', true, true, false)
		require('pasta').config.prev_key = vim.api.nvim_replace_termcodes('<C-p>', true, true, false)
		require('pasta').config.indent_fix = true
	end
})
```

### Steps

1. Open nvim with minimal.lua (from above): `nvim -u minimal.lua ~/.bashrc`
2. Yank a line: `yy`
3. Paste the line: `p`

### Expected Behavior

The yanked line get pasted

### Actual behavior

Nothing happens. Since it doesn't even paste, I can't even try cycling through the ring.

### Vim Info

#### Version

```
$ nvim --version
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim

Run :checkhealth for more info
```
