### ISSUE TITLE
Visual mode pasting - entry appended to the initial text when cycling through history

### ISSUE THREAD

**Issue by makotodejima** [hrsh7th/nvim-pasta#9]
Hello, love the plugin.

I have a problem cycling through history when pasting in visual mode. it would be great if you could give me guidance.
in short, the initial selected range that I pasted the first entry over will come back when start cycling.

given buffer:
```
one
two
three
```

1. select "one", yank "one"
2. select "two", yank "two"
3. select "three", put the first entry "two"
4. "three" is now "two"
5. press `next_key` (<C-n>) to start cycle back to the second entry "one"
6. new "two" becomes "threeone"

ends up as:
```
one
two
threeone
```

expected:
```
one
two
one
```

This does not happen when I use capital V.

only setup I have is:
``` 
vim.keymap.set({ "n", "x" }, "p", require("pasta.mapping").p)
vim.keymap.set({ "n", "x" }, "P", require("pasta.mapping").P)
```

![Kapture 2024-01-16 at 22 03 22](https://github.com/hrsh7th/nvim-pasta/assets/45337313/a6ff1d0e-6cd3-46d8-be7e-5b33aef1ca04)

**Comment by hrsh7th** [comment]
it's valid bug. Thank you for reporting.

I'm investigating it but it's seems to like a vim's bug...

**Comment by makotodejima** [comment]
@hrsh7th brilliant. at first I tried to fix myself but it was unsuccessful.
thanks for fixing this 💯
